table bs140513_032310
	lineageTag: 7db2a449-6e9a-45d2-a357-71c207d38e03

	column step
		dataType: int64
		formatString: 0
		lineageTag: 4b0913e0-7cf6-4323-850e-2d37bcfaef3b
		summarizeBy: sum
		sourceColumn: step

		annotation SummarizationSetBy = Automatic

	column customer
		dataType: string
		lineageTag: 4d209268-6a6c-4d1b-8554-8c8317367bc1
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: 67b1e02f-c7b4-43d9-ab02-2bcc8aa1ca0c
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 593c808b-2a63-4cf1-8bf2-8dfd0c4c6f1e
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column zipcodeOri
		dataType: string
		lineageTag: c7b7f346-dfe4-4e7d-8738-132382eabc01
		summarizeBy: none
		sourceColumn: zipcodeOri

		annotation SummarizationSetBy = Automatic

	column merchant
		dataType: string
		lineageTag: e6a30ee9-a50f-4ffc-be38-8f298852cf6b
		summarizeBy: none
		sourceColumn: merchant

		annotation SummarizationSetBy = Automatic

	column zipMerchant
		dataType: string
		lineageTag: 693f0e02-25d4-4702-948c-a1a8fdaf9beb
		summarizeBy: none
		sourceColumn: zipMerchant

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: c39dbc9d-2d92-45ec-b7c6-f43663be53e0
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 949d7ef6-2ef5-4f7b-83ef-6769c151a905
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fraud
		dataType: int64
		formatString: 0
		lineageTag: 9bb4a651-0398-40b9-8795-75291af6540b
		summarizeBy: sum
		sourceColumn: fraud

		annotation SummarizationSetBy = Automatic

	partition bs140513_032310 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\Power BI Projects\8. Synthetic data from a financial payment system\Assets\bs140513_032310.csv"),[Delimiter=",", Columns=10, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"step", Int64.Type}, {"customer", type text}, {"age", type text}, {"gender", type text}, {"zipcodeOri", type text}, {"merchant", type text}, {"zipMerchant", type text}, {"category", type text}, {"amount", type number}, {"fraud", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

